name: Install Zizmor GitHub action workflow
pipelineid: "{{ .pipelineid }}"

sources:
  zizmor-action:
    kind: githubrelease
    name: Get latest zizmor github action
    spec:
      owner: zizmorcore
      repository: zizmor-action
      versionfilter:
        kind: semver

  zizmor-action-digest:
    dependson:
      - zizmor-action
    name: Get latest GitHub Release digest for zizmorcore/zizmor-action
    kind: githubrelease
    spec:
      key: taghash
      owner: zizmorcore
      repository: zizmor-action
      versionfilter:
        kind: regex
        pattern: '{{ source "zizmor-action" }}'

  checkout-action:
    name: Get latest checkout github action
    kind: githubrelease
    spec:
      owner: actions
      repository: checkout
      versionfilter:
        kind: semver

  checkout-action-digest:
    dependson:
      - checkout-action
    name: Get latest GitHub Release digest for actions/checkout
    kind: githubrelease
    spec:
      key: taghash
      owner: actions
      repository: checkout
      versionfilter:
        kind: semver
        pattern: '{{ source "checkout-action" }}'

targets:
  workflow:
    name: 'install Zizmor gha action {{ source "zizmor-action" }}'
    kind: file
    disablesourceinput: true
    # {{ if .scm.enabled }}
    scmid: default
    # {{ end }}
    spec:
      file: ".github/workflows/zizmor.yaml"
      forcecreate: true
      template: "{{ .gha.template_path }}"
      templatedata:
        checkoutActionVersion: '{{ source "checkout-action" }}'
        checkoutActionDigest: '{{ source "checkout-action-digest" }}'
        zizmorActionVersion: '{{ source "zizmor-action" }}'
        zizmorActionDigest: '{{ source "zizmor-action-digest" }}'
        advancedSecurity: "{{ .gha.advanced_security }}"
        private: "{{ .gha.private }}"
