= README

WARNING: This repository is a work in progress related to Updatecli share&reuse policy feature. It is not ready for production as we may introduce breaking change at any time,

This repository contains a list of common Updatecli published on ghcr.io/updatecli/policies/**

== HOWTO

**Login**

Even though all Updatecli policies published on `ghcr.io` are meant to be public, you'll probably need to authenticate to reduce rate limiting by running:

    docker login ghcr.io

**Publish**

Each policies defines in this repository are automatically published on ghcr.io via a GitHub Action workflow

**Show**

We can see the content of the policy by running:

    updatecli manifest show ghcr.io/updatecli/policies/<a policy name>:latest

**Use**

They are two ways to execute an Updatecli policy, either running one policy or several policies at once.

One policy can be executed by running:

    updatecli apply --config ghcr.io/updatecli/policies/<a policy name>:latest


IMPORTANT: Any values files specified at runtime will override default values setting from the policy bundle

Assuming we have a file named `update-compose.yaml`, multiple policies can be composed and executed by running:
    
        updatecli compose apply

.update-compose.yaml
```yaml
policies:
    - policy: "ghcr.io/updatecli/policies/autodiscovery/golang:latest"
    - policy: "ghcr.io/updatecli/policies/autodiscovery/npm:latest"
```
