name: Default policies

policies:
  - name: Local Updatecli policies
    config:
      - updatecli/updatecli.d
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Updatecli GitHub action version
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1
    valuesinline:
      rootdir: ".github"

  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.8.0@sha256:a4f4e4fcf0950a0eb359ed0518ef789272ea4db1e0bdba048a3772925b81a7aa
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.7.0@sha256:6890c4b4093a80063f518101881098fab8211c986481641faaf797a9ad5a31c3
    values:
      - updatecli/values.d/scm.yaml
