name: Default policies
values:
  - updatecli/values.d/scm.yaml

policies:
  - name: Local Updatecli policies
    config:
      - updatecli/updatecli.d

  - name: Update Updatecli GitHub action version
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1@sha256:869b676074f9fee7edd5d488140a12c3b09a5f8a175f12f26ea85a4f8bd0a9d1
    valuesinline:
      rootdir: ".github"

  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.9.1@sha256:49c07d724474ff7976f7ad5ecb0db9aa46448b456d08f82717913b403a0f02d8

  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0

  - name: Handle GitHub action version update
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1@sha256:869b676074f9fee7edd5d488140a12c3b09a5f8a175f12f26ea85a4f8bd0a9d1

  - name: Configure Updatecli workflows
    id: updatecli
    policy: ghcr.io/updatecli/policies/updatecli/githubaction/scaffold:0.1.0
    valuesinline:
      gha:
        udash:
          enabled: true
        update:
          cron: "0 3 * * *"
          matrix:
            - target_name: "existing pipelines"
              apply_args: "--existing-only=true"
            - target_name: "monitored pipelines"
              apply_args: "--labels=monitor:active"
      pipeline:
        labels:
          ecosystem: "updatecli"
          policy: scaffold
